### ISSUE TITLE
It does not work in Calibre 5.3

### ISSUE THREAD

**Issue by Kurohisui** [yingziwu/doujinshi_metadata_plugins#8]
Decided to upload Calibre to 5.3 and the plug-in won't load.

> calibre, version 5.3.0
> ERROR: Unhandled exception: <b>ImportError</b>:cannot import name 'urlencode' from 'urllib' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)
> 
> calibre 5.3 [64bit]  embedded-python: True is64bit: True
> Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
> ('Windows', '10', '10.0.18362')
> Python 3.8.5
> Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
> Interface language: None
> Successfully initialized third party plugins: Embed Comic Metadata (1, 5, 0)
> Traceback (most recent call last):
>   File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
>   File "calibre\customize\ui.py", line 472, in add_plugin
>   File "calibre\customize\ui.py", line 61, in load_plugin
>   File "calibre\customize\zipplugin.py", line 285, in load
>   File "importlib\__init__.py", line 127, in import_module
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "calibre\customize\zipplugin.py", line 184, in exec_module
>   File "calibre_plugins.dummy1.__init__", line 16, in <module>
> ImportError: cannot import name 'urlencode' from 'urllib' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)`

**Comment by zhjcreator** [comment]
https://1drv.ms/u/s!AhtiqGnVX4ssm3CWNsvAUM1tgsbr?e=YInimv
I used 2tp3.py to convert it into python3.Maybe helpful。

**Comment by LittleFreak** [comment]
> https://1drv.ms/u/s!AhtiqGnVX4ssm3CWNsvAUM1tgsbr?e=YInimv
> I used 2tp3.py to convert it into python3.Maybe helpful。

This fixed it for me, thanks :)
I can now install and use it in Calibre.

**Comment by gin9980** [comment]
> https://1drv.ms/u/s!AhtiqGnVX4ssm3CWNsvAUM1tgsbr?e=YInimv I used 2tp3.py to convert it into python3.Maybe helpful。
tried using this but it comes up with an error when fetching metadata

**Comment by xerance** [comment]
Anyone got this working for callibre  5.42?
